name: Generate SBOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install root dependencies
        run: npm install --legacy-peer-deps
        
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
          cd ..
        
      - name: Install CycloneDX
        run: npm install -g @cyclonedx/cyclonedx-npm
        
      - name: Generate SBOM
        run: cyclonedx-npm --output-file bom.json
        
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.json 